// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestBackend.Context;

#nullable disable

namespace TestBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241214233710_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestBackend.Entities.Students", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DocumentType = 1,
                            Email = "juan@gmail.com",
                            Name = "Juan",
                            Passport = "87049862Z",
                            Surname = "Garcia Garcia"
                        },
                        new
                        {
                            StudentId = 2,
                            DocumentType = 1,
                            Email = "pedro@gmail.com",
                            Name = "Pedro",
                            Passport = "36289717H",
                            Surname = "Gonzalez Gonzales"
                        },
                        new
                        {
                            StudentId = 3,
                            DocumentType = 2,
                            Email = "antonio@gmail.com",
                            Name = "Antonio",
                            Passport = "444444444A",
                            Phone = "677777775",
                            Surname = "Diaz Diaz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
